pipeline {
    agent any

    environment {
        GRADLE_USER_HOME = "${WORKSPACE}/.gradle"
    }

    stages {
        stage('Clone code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Binh2408/test_jenkins'
            }
        }

        stage('Grant Permission for Gradle') {
            steps {
                dir('test_jenkins') {
                    sh 'chmod +x ./gradlew'
                }
            }
        }

        stage('Build') {
            steps {
                dir('test_jenkins') {
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('test_jenkins') {
                    sh './gradlew bootJar'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'test_jenkins/build/libs/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo "🎉 Build Spring Boot (Gradle) thành công!"
        }
        failure {
            echo "❌ Build Spring Boot thất bại!"
        }
    }
}
